### ISSUE TITLE
Vermittelte kommunikative Fähigkeiten klarer definieren oder entfernen

### ISSUE THREAD

**Issue by mattes3** [isaqb-org/curriculum-swarc4ai#10]
In `01-what-to-expect-of-this-module.adoc` fiel mir folgender Satz auf:

> Sie sind mithilfe der vermittelten kommunikativen Fähigkeiten in der Lage, eine einheitliche Sprache zwischen Data Scientists, KI-Expert:innen und Softwareentwickler:innen zu etablieren. 

Das klingt als würden im Kurs auch kommunikative Fähigkeiten gelehrt. Wenn ich jedoch im Lehrplan nach `Sprache` oder `kommunika` suche, finde ich nichts.

Ist das evtl. veraltet und kann entfernt werden?

**Comment by mahboubagharbi** [comment]
Wir werden das prüfen!

**Comment by magnusse** [comment]
Ich habe den Satz rausgenommen, veraltet, danke.
