### ISSUE TITLE
Tippfehler in LZ 1-4 entfernen

### ISSUE THREAD

**Issue by mattes3** [isaqb-org/curriculum-swarc4ai#11]
Dort steht:

> LZ 1-4: Kennen Einsatzmöglichkeiten in Endnutzeranwendungen, z.B. bSprachassistenten (Chatbots) und Empfehlungssysteme (Recommender Engine).

Streiche das kleine 'b' vor den `Sprachassistenten`.

**Comment by mahboubagharbi** [comment]
Ok

**Comment by magnusse** [comment]
done.
