### ISSUE TITLE
Lernziel 2-12 besser formulieren

### ISSUE THREAD

**Issue by mattes3** [isaqb-org/curriculum-swarc4ai#12]
https://github.com/isaqb-org/curriculum-swarc4ai/blob/main/docs/02-module-block-2/02-learning-goals.adoc#lz-2-12-wissen-wie-man-ai-risk-minimierung-strategien-entwickelt-und-anwendet

Dort steht:

> Wissen, wie man AI-Risk Minimierung Strategien entwickelt und anwendet.

Ersetzen durch:

`Wissen, wie man Strategien zur AI-Risikominimierung entwickelt und anwendet.`

**Comment by mahboubagharbi** [comment]
Ok, finde auch besser.

**Comment by magnusse** [comment]
Ich habe jetzt umformuliert:

"Die Teilnehmer:innen können Strategien zur AI-Risikominimierung entwickeln und anwenden."

**Comment by programming-wolf** [comment]
Verbesserungsvorschlag:

> Strategien zur AI-Risikominimierung entwickeln und anwenden

Ich stelle mir immer die Frage (innerlich) "was sollen die Teilnehmende lernen, was ist das Lernziel?" und die einzelnen Lernziele sollen Antworten auf diese Frage sein. (Und ohne Punkt, da es eine Überschrift ist)

Im Lernziel selbst könnt ihr dann 1-x Sätze schreiben, was darin vorkommen soll.

**Comment by magnusse** [comment]
Hmm, ja verstehe ich. Es ist natürlich immer eine Gratwanderung, ob wir etwas tiefer erklären, was genau geschult werden soll, oder ob wir das dem Schulungsanbieter offen lassen. Für das Beispiel oben habe ich jetzt nochmal etwas ergänzt, weil ihr da vielleicht ein bisschen recht habt. In den anderen Curricula, die ich kenne, ist das aber auch oft sehr offen gehalten. Mit genaueren Beschreibungen werden ja auch immer die Freiheitsgrade der Schulungsanbieter eingeschränkt.
