### ISSUE TITLE
Lernziel 6-2: Präzisieren, was strategisches Design und Context Maps mit KI-Architektur zu tun haben

### ISSUE THREAD

**Issue by mattes3** [isaqb-org/curriculum-swarc4ai#14]
Als Trainer für DDD habe ich mich gefreut, dass ein Lernziel auch mit DDD zu tun hat, doch ich habe mich gefragt: Was hat das Lernziel genau zu bedeuten?

Es sollen anscheinend zwei Dinge damit bestimmt und dokumentiert werden:

- Art der Integration von KI-Systemen
- Grad der Integration von KI-Systemen

Was genau ist damit gemeint? Eine kurze Definition in ein bis zwei Sätzen würde hier helfen.

**Comment by mahboubagharbi** [comment]
Wir werden das prüfen. Eventuell streichen wir DDD ganz.

**Comment by magnusse** [comment]
Im Text steht  "Können das strategische Design von DDD (insbesondere Context Maps) einsetzen, um die
Art und den Grad der Integration von KI-Systemen zu bestimmen und zu dokumentieren." . Das bedeutet, dass die Teilnehmer:innen ein KI-System als Teil einer Gesamtarchitektur betrachten können und in der Lage sind, einzelne Subdomänen mit KI-Lösungen zu versehen. Dabei müssen auch die Schnittstellen zu klassichen Softwaresystemen entworfen und in der Zusammenarbeit definiert werden. Ich würde DDD hier als optional betrachten, aber eine Methodik zum Einfügen einer KI-(Teil-)Lösung in eine Gesamtarchitektur sollte m.E. irgendwie gelehrt werden.

**Comment by magnusse** [comment]
Ich habe das jetzt umformuliert und das LZ als Optional gekennzeichnet.
