### ISSUE TITLE
Seite 1 umnummerieren, so dass die neue Seite 1 nach rechts zu liegen kommt

### ISSUE THREAD

**Issue by mattes3** [isaqb-org/curriculum-swarc4ai#15]
Kleines Detail für die Druckaufbereitung als PDF:

Die Seite mit der Nummer `1` liegt momentan bei doppelseitigem Ausdruck links anstatt rechts. Wenn man sie umnummeriert, so dass sie die Nummer `iv` trägt, dann passt alles, weil aus der Seite `2` dann die Seite `1` wird.

**Comment by programming-wolf** [comment]
Das ist was für das grundsätzliche Template in iSAQB-org/advanced-template 

Schaue ich mir bei Gelegenheit an.

**Comment by mahboubagharbi** [comment]
Ok. Danke

**Comment by programming-wolf** [comment]
Hier mit aufgenommen: 
https://github.com/isaqb-org/advanced-template/issues/164
