### ISSUE TITLE
MLOps-Pipeline kann ein Riesenthema werden, besser auf LZ 5-23 verzichten?

### ISSUE THREAD

**Issue by mattes3** [isaqb-org/curriculum-swarc4ai#16]
In Abschnitt 5 "Skalierbarkeit und Leistungsoptimierung von KI-Systemen" gibt es Lernziel 5-23:

> Erfahren anhand eines Praxisbeispiels, wie eine MLOps-Pipeline aussehen kann und welche Einsichten diese auf die Parameter, Metriken usw. bietet.

Das kann meines Erachtens sehr komplex werden und im Kurs in zeitliche Bedrängnis führen. Vielleicht besser darauf verzichten.

**Comment by mahboubagharbi** [comment]
Wir werden ohnehin Pflicht- und optionale Inhalte definieren. Dabei entscheiden wir, welche Themen sinnvollerweise verpflichtend sind und welche als optional behandelt werden können. Die Anbieter haben die Freiheit, die Schulung entweder über 4 oder 5 Tage anzubieten, wobei die Mindestdauer 3 Tage beträgt.

**Comment by mattes3** [comment]
Dieser Issue wurde als `completed` geschlossen. Leider ist das Lernziel nicht als optional markiert. Deshalb öffne ich ihn noch einmal.

**Comment by mattes3** [comment]
Ach, das war ein Fehler von mir beim Generieren mit Gradle! Jetzt habe ich die richtige Version, und da ist es in der Tat optional. Danke!
