### ISSUE TITLE
Konsistenz der Begriffe

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-swarc4ai#19]
Es wird über den gesamten Lehrplan mal von AI, mal von KI gesprochen. Dies sollte – bis auf Eigennamen, wie bspw. EU AI Act – vereinheitlicht werden, dass überall im deutschsprachigen Lehrplan von KI die Rede ist. 

Das hätte ich gerne noch für das Release behoben.

**Comment by magnusse** [comment]
Habe ich umgesetzt, allerdings habe ich AI im Text gelassen, wenn damit ein englischer Fachbegriff beschrieben wird (AI-safety, Agentic AI Software Architekturen, explainable AI). Allerdings wird AI meistens mit einem englischen Fachbegriff verwendet, so dass ich nicht so viele Stellen geändert habe.
