### ISSUE TITLE
Weitere Reduzierung der Anzahl von Lernzielen und Entfernen von Dopplungen

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-swarc4ai#20]
Ihr sollte, als Konsortium, noch einmal über den gesamten Lehrplan schauen und dabei folgende Gesichtspunkte nochmal analysieren:

* Doppelte Lernziele entfernen. Bspw. sind Lernziel 3-22 (Effiziente KI-Modelle und -Systeme entwerfen) und Lernziel 5.4 (Kosten, Stromverbrauch und nachhaltige Nutzung von KI verstehen) in meinen Augen effektiv das gleiche bzw. sehr ähnlich, und können zusammengefasst werden.
* Überprüfen der Hauptkapitelüberschrift und der jeweiligen Lernziele: passen die Lernziele in dieser Form noch zu den Überschriften?
* Einige Lernziele sind irgendwie ähnlich oder können zu einem zusammengefasst werden, beispielsweise Lernziel 3-3 (Arten von Daten und typische ML-Probleme kennen) sowie Lernziel 3-4 (Anforderungen an Daten für ML kennen). Für mich als Laien sind das Themen, die durchaus in ein Lernziel verpackt werden können, mit dann etwas ausführlicher Erklärung, was in dem Lernziel alles vermittelt werden soll

Vor allem betrifft das Umfangthema Kapitel 3, 5 und 6.

Das wäre noch ein super Punkt für das initiale Release, dann habt ihr einen wirklich starken Lehrplan aufgestellt! 🥳

**Comment by mahboubagharbi** [comment]
Danke! @visenger : du wolltest ja was noch machen, willst du bitte übernehmen?
