### ISSUE TITLE
Release Notes erstellen

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-swarc4ai#22]
Wir brauchen noch saubere Release Notes. Dazu bitte am besten die Datei [CHANGELOG.md](https://github.com/isaqb-org/curriculum-swarc4ai/blob/main/CHANGELOG.md) anpassen. Ihr könnt hier Markdown verwenden, das wird dann alles in das GitHub Release mit reingezogen.

**Comment by magnusse** [comment]
Habe ich geschrieben in die changelog.md.
