### ISSUE TITLE
Separate learning goal names from learning goal content 

### ISSUE THREAD

**Issue by StefanZoerner** [isaqb-org/curriculum-swarc4ai#3]
Currently, the name of a learning goal is identical to the content for almost all learning goals. Enumerations and examples are also included. This leads to a long overview of the learning goals at the beginning of the document (5+ pages). As a consequence, the overview does not fulfill its purpose.

Example:

```
[[LZ-1-5]]
==== LZ 1-5: Wissen, wie man Risiken bei der Anwendung von KI (Halluzinationen, Bias, Fairness…) 
und gesellschaftlichen Risiken (Deepfakes, AI-enabled Cyberattacs, Safety Risks in Critical Systems, 
Social Manipulation, Intellectual Property Issues, etc.) identifiziert.
```

I would split it up, for example like this

```
[[LZ-1-5]]
==== LZ 1-5: Risiken bei der Anwendung von KI identifizieren

Die Teilnehmer:innen wissen, wie man Risiken bei der Anwendung von KI wie z.B.

- Halluzinationen
- Bias
- Fairness

und gesellschaftlichen Risiken wie z.B.

- Deepfakes
- AI-enabled Cyberattacs
- Safety Risks in Critical Systems
- Social Manipulation
- Intellectual Property Issues

identifiziert.
```

**Comment by programming-wolf** [comment]
Another example:

> LZ 3.4: (R1) Wissen, wie KI-Systeme nach EU AI Act Risikolevel (verboten, hochrisikoreich, begrenzt risikoreich, niedrigrisikoreich) klassifiziert werden und welche regulatorischen Anforderungen jeweils gelten.

Should look like this:
> LZ 3.4: Klassifikation von KI-Systemen nach EU AI Act Risikolevel nachvollziehen und regulatorische Anforderungen kennen
> Teilnehmende lernen die Risikolevel _verboten_, _hochrisikoreich_, _begrenzt risikoreich_ und _niedrigrisikoreich_ kennen und wissen, welche regulatorischen Anforderungen diese nach sich ziehen.

**Comment by magnusse** [comment]
Habe ich umgebaut, gerne Feedback, ob das so euren Vorstellungen entspricht.

**Comment by programming-wolf** [comment]
Passt soweit, danke!
