### ISSUE TITLE
Lernziele zusammenfassen und Inhalte reduzieren

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-swarc4ai#5]
Bei Kapitel 3 ist mir aufgefallen, dass es eine Unterteilung in funktionale und nicht-funktionale (Das heißt doch laut Foundation-Level Qualitätsanforderungen 😉  ) sowie Vorgehen bei ML gibt. 
Diese Unterteilung würde ich weglassen und versuchen, die doch recht vielen Lernziele zusammenzufassen und vielleicht auch etwas zu reduzieren. 

Die Lernziele  LZ 3.10, LZ 3.11, LZ 3.12 und LZ 3.13 ließen sich z.B. super in ein einzelnes Lernziel verpacken, das dafür etwas mehr Beschreibungstext hat. 

29 Seiten Lehrplan ist schon relativ groß, das haben wir auch bei DATA bemängelt. Da besteht schnell die Gefahr, dass der Lehrplan einerseits zu umfangreich ist und andererseits die Inhalte dann nicht mehr ausreichend in 3 Tagen Training behandelt werden können.

**Comment by mattes3** [comment]
Stimmt. Als ich den Lehrplan las, habe ich einmal geprüft, wie viele Minuten pro Lernziel bleiben:

- Kapitel 1: 9 min.
- Kapitel 2: 6 min.
- Kapitel 3: 13 min.
- Kapitel 4: 11 min.
- Kapitel 5: 6 min.
- Kapitel 6: 8 min.

Ich finde, das geht zu schnell. Alles unter 10-15 Min. pro Lernziel finde ich unrealistisch.

**Comment by mahboubagharbi** [comment]
Deshalb möchten wir Pflicht- und optionale Inhalte definieren. Die Dauer der Schulung kann zwischen 3 und 5 Tagen variieren. @programming-wolf : wie sollen Pflicht- und optionale Teile sinnvoll kennzeichnen?

**Comment by programming-wolf** [comment]
Ich würde direkt beim Lernziel das mit angeben, also irgendwie so:

L-Z 5-07: [OPTIONAL] XY mit Z und auch Teilen von C kombinieren

Die optionalen Lernziele eines Kapitels würde ich dann – wenn möglich – immer ans Ende packen.

**Comment by programming-wolf** [comment]
Ist schon besser geworden, ich eröffne noch weitere Tickets mit Punkten, die mir aufgefallen sind.
