### ISSUE TITLE
Beispielübungen reduzieren / entfernen

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-swarc4ai#6]
Die Beispielübungen sind schon sehr detailliert und wirken wie aus einem Übungsblatt eines Trainings.

Die würde ich aus dem Curriculum rausnehmen, damit alle TPs sich selbst was ausdenken können (und müssen!).

**Comment by mattes3** [comment]
Was meinst Du hier genau? Kannst Du eine Stelle als Beispiel nennen?

**Comment by programming-wolf** [comment]
Guter Punkt, die haben wie beim Übernehmen nach asciidoc wohl schon rausgefiltert. 🙃
