### ISSUE TITLE
Struktur der Lernziele

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-swarc4ai#7]
Die ursprüngliche Unterteilung in _Wissen_, _Verstehen_, _Kennen_ gibt es in der Form nicht mehr und soll aus den Lehrplänen verschwinden. 

Natürlich dürfen die Verben in den Lernzielen weiterhin verwendet werden, da es manchmal einfach passend ist. Aber dass in einem Lernziel

Die Teilnehmer:innen kennen... 
Die Teilnehmer:innen können...
Die Teilnehmer:innen wissen... 

steht, wollen wir zukünftig nicht mehr haben. Lieber eine exaktere Formulierung der Lernziele mit beschreibendem Hilfstext oder Stichpunkten (wenn nötig) wie in #3  beschrieben.

**Comment by mattes3** [comment]
Das mit den Verben war aus Sicht eines Trainers aber sehr praktisch!

- Wenn ich lesen "wissen", dann weiß ich, dass ich den Teilnehmern das lediglich erzählt oder gezeigt haben muss.
- Wenn da "verstehen" steht, muss ich das Verständnis auch durch eine kleine Übung oder etwas Entsprechendes prüfen. 
- Wenn da "können" steht, muss ich die Teilnehmer das auch tatsächlich selbst ausprobieren und Fehler machen lassen, und ich muss als Trainer Feedback dazu geben.

Diese Steigerung als Trainer zu kennen ist aus meiner Sicht sehr wichtig. Warum sollte man diese wichtige Info weglassen? Ist mir nicht ersichtlich.

**Comment by programming-wolf** [comment]
Diese Verben dürfen ja weiterhin verwendet werden, in einigen Lernzielen wird `kennen` oder `verstehen` sicher auftauchen. Fehlen diese, ist es implizit ein "können". 
Das hilft, die Lernziele kleiner zu schneiden und fokussierter zu formulieren.

**Comment by mattes3** [comment]
Ah, das hört sich gut an! :-)

**Comment by mahboubagharbi** [comment]
@programming-wolf : "Die ursprüngliche Unterteilung in Wissen, Verstehen, Kennen gibt es in der Form nicht mehr und soll aus den Lehrplänen verschwinden." Wo steht das?

**Comment by magnusse** [comment]
Ich habe die gesamten Lernziele wie in #3 beschrieben umgebaut. Ich hoffe das passt zu euren Vorstellungen. Dadurch wird auch der Punkt von Stefan in #3 adressiert, dass die Überschriften kürzer und ohne Verb beschrieben werden.

**Comment by programming-wolf** [comment]
sehr gut gelöst, ist behoben.
