### ISSUE TITLE
Literatur-Referenzen eindeutig machen

### ISSUE THREAD

**Issue by mattes3** [isaqb-org/curriculum-swarc4ai#8]
Im Text fand ich häufig Referenzen, die (zumindest nach dem Ausdrucken des Lehrplans) gleich heißen aber verschiedene Werke bezeichnen. Ich finde, jedes referenzierte Werk sollte eine eindeutige ID haben.

Beispiel:

```
[Hotz] N. Hotz: 15 Data Science Documentation Best Practices https://www.datascience-pm.com/documentation-best-practices/
[Hotz] N. Hotz: What is a Data Science Life Cycle? https://www.datascience-pm.com/data-science-life-cycle/
[Hotz] N. Hotz: What is TDSP https://www.datascience-pm.com/tdsp/
```

Wenn man diese im Text benutzt, sehen sie alle wie `[Hotz]` aus, obwohl es drei verschiedene Werke sind. Ich habe gesehen, dass sie intern als `hotz-one` bis `hotz-three` benutzt werden, doch das kann man als Leser nicht erkennen.

Es gibt Leute, die dieses Problem schon gelöst und Regeln dafür erfunden haben:
https://www.scribbr.co.uk/referencing/harvard-bibliography/

Zum Beispiel:

> How do I cite multiple sources by the same author published in the same year?
>
> In [Harvard style referencing](https://www.scribbr.co.uk/referencing/harvard-style/), to distinguish between two sources by the same author that were published in the same year, you add a different letter after the year for each source:
>
>        (Smith, 2019a)
>        (Smith, 2019b)
>
> Add ‘a’ to the first one you cite, ‘b’ to the second, and so on. Do the same in your [bibliography or reference list](https://www.scribbr.co.uk/referencing/harvard-bibliography/).

**Comment by mahboubagharbi** [comment]
Ok, wir prüfen.

**Comment by programming-wolf** [comment]
Hab das mal versucht umzusetzen. Ist jetzt auf alle Fälle eindeutig.

**Comment by mattes3** [comment]
Hat funktioniert, danke!
